Fix logic for Blender 5.2+
Avoid error:
```python
Traceback (most recent call last):

  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_1.1.6\ayon_blender\api\ops.py", line 126, in execute
    result = callback(*args, **kwargs)

  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_1.1.6\ayon_blender\plugins\load\load_blend.py", line 237, in exec_update
    self.exec_remove(container)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^

  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_1.1.6\ayon_blender\plugins\load\load_blend.py", line 321, in exec_remove
    getattr(bpy.data, attr).remove(data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: bpy_prop_collection: attribute "remove" not found
```

Also fix error with `BLENDER_EEVEE_NEXT` found found in render engine enum because it's renamed back to `BLENDER_EEVEE`